version: '3.8'

services:
  t1-database:
    image: postgres:15-alpine
    container_name: t1-database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=t1_db
      - POSTGRES_USER=t1
      - POSTGRES_PASSWORD=t1
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U deveducate" ]
        interval: 10s
        timeout: 5s
        retries: 3