spring:
  application:
    name: intensive

  datasource:
    url: jdbc:postgresql://localhost:5432/t1_db
    username: t1
    password: t1
    hikari:
      auto-commit: false

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html